# This is a basic workflow to help you get started with Actions

name: Check APIC Toolkit

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install-apic-toolkit:
    runs-on: ubuntu-latest
    steps:
      - name: Check NPM version
        run: npm --version
      - name: Install Node 11
        run: npm install -g node@11.15.0
      - name: Check Node Version
        run: node --version
      - name: Install APIC toolkit
        run: npm install -g apiconnect
      - name: Check APIC toolkit Version
        run: apic --version
