# This is a basic workflow to help you get started with Actions

name: Check APIC Toolkit

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install-apic-toolkit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '11.15.0'
      - name: Check APIC toolkit Version
        run: yes | apic --version
