# This is a basic workflow to help you get started with Actions

name: Check APIC Toolkit

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  install-apic-toolkit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check NPM version
        run: npm --version
      - name: Install Node 11
        run: npm i node@11.15.0
      - name: Check Node Version
        run: node --version
      - name: Install APIC
        run: npm i apiconnect
      - name: Check APIC Version
        run: apic --version
